services:
  mongodb:
    image: mongo:latest
    container_name: cs-340-mongodb-companies
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P0werF!ex3123_
    volumes:
      - mongodb_data:/data/db
      - ./datasets:/datasets
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: cs-340-mongo-express-companies
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: P0werF!ex3123_
      ME_CONFIG_MONGODB_URL: mongodb://admin:P0werF!ex3123_@mongodb:27017/
    networks:
      - mongo-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongo-network:
    driver: bridge
